const state={cases:[],detail:null,tab:'content',caseQuery:new URLSearchParams(),nextCases:'',timelineQuery:new URLSearchParams(),nextEvents:''};
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const labels={draft:'草稿',audited:'已审查',remediating:'整改中',review:'待复核',approved:'已批准',published:'已发布',open:'待整改',submitted:'待复核',accepted:'已接受',returned:'已退回'};
const eventLabels={'case.created':'建立验收案','case.metadata_updated':'更新验收案信息','content.saved':'保存内容修订','content.restored':'回退内容修订','audit.completed':'完成规则审查','audit.recompleted':'完成增量复审','evidence.submitted':'提交整改证据','evidence.batch_submitted':'批量提交整改证据','issue.reviewed':'复核整改证据','issue.batch_reviewed':'批量复核整改证据','case.approved':'批准验收案','declaration.published':'发布合格声明'};
function id(){return crypto.randomUUID()}
function toast(message,error=false){const node=$('#toast');node.textContent=message;node.style.background=error?'#842c27':'#17211d';node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2800)}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json();if(!response.ok){const message=data.error?.fields?.map(x=>`${x.field}：${x.message}`).join('；')||data.error?.message||'请求失败';throw new Error(message)}return data}
function paramsFrom(form){const values=new URLSearchParams();for(const [key,value] of new FormData(form)){if(String(value).trim())values.set(key,String(value).trim())}return values}
async function loadCases(selectID,append=false){const query=new URLSearchParams(state.caseQuery);if(append&&state.nextCases)query.set('cursor',state.nextCases);const data=await api(`/api/cases?${query}`);state.cases=append?[...state.cases,...data.cases]:data.cases;state.nextCases=data.next_cursor||'';renderCases(data.total);if(selectID)await openCase(selectID)}
function renderCases(total=state.cases.length){const root=$('#cases');root.innerHTML='';$('#case-count').textContent=total;for(const item of state.cases){const button=document.createElement('button');button.className='case-item'+(state.detail?.case.id===item.id?' active':'');const overdue=item.overdue?' · 已逾期':'';button.innerHTML=`<strong>${escapeHTML(item.title)}</strong><span>${escapeHTML(item.organization)} · ${labels[item.status]||item.status}${overdue}</span><small>${escapeHTML(item.next_role||'流程已关闭')}</small>`;button.onclick=()=>openCase(item.id);root.append(button)}$('#next-cases').classList.toggle('hidden',!state.nextCases)}
async function openCase(caseID){state.detail=await api(`/api/cases/${caseID}`);$('#empty-state').classList.add('hidden');$('#detail').classList.remove('hidden');renderCases();renderDetail()}
function renderDetail(){const d=state.detail,c=d.case;$('#case-org').textContent=c.organization;$('#case-title').textContent=c.title;$('#case-meta').textContent=`负责人：${c.owner} · 目标发布：${c.target_publish_date} · 聚合修订 ${c.revision} · 内容修订 ${c.content_revision}`;$('#case-status').textContent=labels[c.status]||c.status;$('#issue-count').textContent=c.issues?.length||0;renderBlocks();renderHistory();renderIssues();renderTimeline(d.timeline,d.timeline_integrity);setTab(state.tab);const canAudit=c.status==='draft'&&d.content||c.status==='remediating'&&c.content_revision>c.audit_content_revision;$('#run-audit').disabled=!canAudit;$('#run-audit').textContent=c.status==='remediating'?'再次审查':'执行规则审查';$('#save-content').disabled=!['draft','remediating'].includes(c.status);$('#approve').disabled=c.status!=='review'||!allAccepted(c);$('#publish').disabled=c.status!=='approved';$('#preview-declaration').disabled=c.status!=='review'&&c.status!=='approved'&&c.status!=='published';$('#batch-evidence').disabled=!$$('.batch-evidence-select').length;$('#batch-review').disabled=!$$('.batch-review-select').length}
function blockTemplate(block={id:`block-${id().slice(0,8)}`,type:'paragraph',text:'',heading_level:1,link_target:'',alt_text:'',table_headers:[]}){const row=document.createElement('div');row.className='block';row.dataset.id=block.id;row.innerHTML=`<select class="block-type" aria-label="内容类型"><option value="heading">标题</option><option value="paragraph">段落</option><option value="link">链接</option><option value="image">图片</option><option value="table">表格</option></select><div class="block-fields"></div><button class="icon remove-block" aria-label="删除内容块">×</button>`;$('.block-type',row).value=block.type;$('.block-type',row).onchange=()=>renderBlockFields(row,{...block,type:$('.block-type',row).value});$('.remove-block',row).onclick=()=>row.remove();renderBlockFields(row,block);return row}
function renderBlockFields(row,block){const fields=$('.block-fields',row);fields.innerHTML='';const field=(name,label,value,wide=false)=>{const wrap=document.createElement('label');if(wide)wrap.className='wide';wrap.textContent=label;const input=document.createElement('input');input.dataset.field=name;input.value=value||'';wrap.append(input);fields.append(wrap)};switch($('.block-type',row).value){case'heading':field('text','标题文本',block.text,true);field('heading_level','标题层级（1-6）',block.heading_level||1);break;case'paragraph':field('text','段落文本',block.text,true);break;case'link':field('text','链接文本',block.text);field('link_target','链接目标',block.link_target);break;case'image':field('text','图片说明',block.text);field('alt_text','替代文本',block.alt_text);break;case'table':field('text','表格说明',block.text);field('table_headers','列标题（用逗号分隔）',(block.table_headers||[]).join(','),true)}}
function renderBlocks(){const root=$('#blocks');root.innerHTML='';const blocks=state.detail.content?.blocks||[];for(const block of blocks)root.append(blockTemplate(block));if(!blocks.length)root.append(blockTemplate({id:'heading-1',type:'heading',text:state.detail.case.title,heading_level:1}))}
function collectBlocks(){return $$('.block').map(row=>{const type=$('.block-type',row).value;const value=name=>$(`[data-field="${name}"]`,row)?.value||'';const block={id:row.dataset.id,type};if(['heading','paragraph','link','image','table'].includes(type))block.text=value('text');if(type==='heading')block.heading_level=Number(value('heading_level'));if(type==='link')block.link_target=value('link_target');if(type==='image')block.alt_text=value('alt_text');if(type==='table')block.table_headers=value('table_headers').split(',').map(x=>x.trim()).filter(Boolean);return block})}
function renderHistory(){const revisions=state.detail.content_revisions||[],root=$('#history-list'),from=$('#diff-from'),to=$('#diff-to');root.innerHTML='';from.innerHTML='';to.innerHTML='';for(const item of revisions){for(const select of [from,to]){const option=document.createElement('option');option.value=item.revision;option.textContent=`第 ${item.revision} 版`;select.append(option)}const row=document.createElement('div');row.className='history-row';row.innerHTML=`<span><strong>第 ${item.revision} 版</strong> · ${escapeHTML(item.saved_by||'未知保存人')} · ${item.block_count} 个内容块 · ${new Date(item.saved_at).toLocaleString('zh-CN')}</span>`;const button=document.createElement('button');button.textContent='以此版本回退';button.disabled=!['draft','remediating'].includes(state.detail.case.status)||item.revision===state.detail.case.content_revision;button.onclick=()=>restoreContent(item.revision);row.append(button);root.append(row)}if(revisions.length){from.value=revisions[0].revision;to.value=revisions[revisions.length-1].revision}}
async function restoreContent(sourceRevision){if(!confirm(`确认以第 ${sourceRevision} 版内容生成新的修订？`))return;const c=state.detail.case;await mutate(`/api/cases/${c.id}/content/restore`,{revision:c.revision,source_revision:sourceRevision,actor:c.owner,request_id:id()})}
function allAccepted(c){return(c.issues||[]).every(issue=>issue.status==='accepted'&&issue.evidence?.content_revision===c.content_revision)}
function renderIssues(){const root=$('#issues');root.innerHTML='';const c=state.detail.case,issues=c.issues||[];if(c.last_audit_difference){const diff=document.createElement('div');diff.className='audit-diff';diff.textContent=`本次复审：已消除 ${c.last_audit_difference.resolved.length} 项，持续存在 ${c.last_audit_difference.persistent.length} 项，新增 ${c.last_audit_difference.added.length} 项`;root.append(diff)}if(!issues.length){root.insertAdjacentHTML('beforeend','<p class="muted">规则审查未发现问题。可直接批准验收。</p>');return}for(const issue of issues){const node=document.createElement('article');node.className='issue '+issue.status;const selectable=['open','returned'].includes(issue.status)?'<input class="batch-evidence-select" type="checkbox" aria-label="选择批量提交">':issue.status==='submitted'?'<input class="batch-review-select" type="checkbox" aria-label="选择批量复核">':'';node.innerHTML=`<div class="issue-head"><div class="issue-select">${selectable}<div><h3>${escapeHTML(issue.message)}</h3><span class="issue-code">${escapeHTML(issue.rule_code)} · 内容块 ${escapeHTML(issue.block_id)}</span></div></div><span class="badge">${labels[issue.status]||issue.status}</span></div>`;node.dataset.issueId=issue.id;if(issue.evidence){const view=document.createElement('div');view.className='evidence-view';view.innerHTML=`<strong>${escapeHTML(issue.evidence.description)}</strong><p>${escapeHTML(issue.evidence.text)}</p><small>基于内容修订 ${issue.evidence.content_revision}，提交人 ${escapeHTML(issue.evidence.submitted_by)}</small>`;node.append(view)}if(['open','returned'].includes(issue.status))node.append(evidenceForm(issue));if(issue.status==='submitted')node.append(reviewForm(issue));root.append(node)}}
function evidenceForm(issue){const form=document.createElement('form');form.className='evidence-form';form.innerHTML='<input name="description" placeholder="整改说明" required><input name="actor" placeholder="提交人" value="内容编辑" required><textarea name="text" placeholder="文本证据" required></textarea><div class="evidence-actions"><button class="primary">提交证据</button></div>';form.onsubmit=async event=>{event.preventDefault();const values=new FormData(form);await mutate(`/api/cases/${state.detail.case.id}/issues/${issue.id}/evidence`,{revision:state.detail.case.revision,content_revision:state.detail.case.content_revision,description:values.get('description'),text:values.get('text'),actor:values.get('actor'),request_id:id()})};return form}
function reviewForm(issue){const form=document.createElement('form');form.className='evidence-form review-form';form.innerHTML='<input name="reviewer" placeholder="审核员" value="质量审核员" required><input name="comment" placeholder="复核意见（退回时必填）"><label>批量决定<select name="batch_decision"><option value="accept">接受</option><option value="return">退回</option></select></label><div class="evidence-actions"><button name="decision" value="accept" class="primary">接受证据</button><button name="decision" value="return">退回整改</button></div>';form.onsubmit=async event=>{event.preventDefault();const values=new FormData(form);await mutate(`/api/cases/${state.detail.case.id}/issues/${issue.id}/review`,{revision:state.detail.case.revision,accept:event.submitter.value==='accept',reviewer:values.get('reviewer'),comment:values.get('comment'),request_id:id()})};return form}
async function batchEvidence(){const selected=$$('.batch-evidence-select:checked').map(box=>box.closest('.issue'));if(!selected.length){toast('请选择待整改问题',true);return}const items=selected.map(node=>{const form=$('.evidence-form',node),values=new FormData(form);return{issue_id:node.dataset.issueId,description:values.get('description'),text:values.get('text'),content_revision:state.detail.case.content_revision}});const actor=new FormData($('.evidence-form',selected[0])).get('actor');await batchMutate(`/api/cases/${state.detail.case.id}/evidence/batch`,{revision:state.detail.case.revision,content_revision:state.detail.case.content_revision,actor,request_id:id(),items})}
async function batchReview(){const selected=$$('.batch-review-select:checked').map(box=>box.closest('.issue'));if(!selected.length){toast('请选择待复核问题',true);return}const decisions=selected.map(node=>{const values=new FormData($('.review-form',node));return{issue_id:node.dataset.issueId,accept:values.get('batch_decision')==='accept',comment:values.get('comment')}});const reviewer=new FormData($('.review-form',selected[0])).get('reviewer');await batchMutate(`/api/cases/${state.detail.case.id}/reviews/batch`,{revision:state.detail.case.revision,reviewer,request_id:id(),decisions})}
async function batchMutate(path,body){try{await api(path,{method:'POST',body:JSON.stringify(body)});await openCase(state.detail.case.id);await loadCases();toast('批量操作已保存')}catch(error){toast(error.message,true)}}
function renderTimeline(events=state.detail.timeline,integrity=state.detail.timeline_integrity){const root=$('#timeline');root.innerHTML='';const status=$('#timeline-integrity');status.textContent=integrity?.valid?'事件日志完整':`完整性异常：${(integrity?.errors||[]).join('；')}`;status.classList.toggle('error',!integrity?.valid);for(const event of events){const li=document.createElement('li');const details=document.createElement('details');details.innerHTML=`<summary><strong>${eventLabels[event.event_type]||escapeHTML(event.event_type)}</strong><span>${escapeHTML(event.actor)} · ${new Date(event.occurred_at).toLocaleString('zh-CN')} · 修订 ${event.case_revision}</span></summary><dl><dt>request_id</dt><dd>${escapeHTML(event.request_id||'无')}</dd><dt>case_revision</dt><dd>${event.case_revision}</dd><dt>业务载荷</dt><dd><pre>${escapeHTML(JSON.stringify(event.payload||{},null,2))}</pre></dd></dl>`;li.append(details);root.append(li)}$('#next-events').classList.toggle('hidden',!state.nextEvents)}
async function loadTimeline(append=false){const query=new URLSearchParams(state.timelineQuery);if(append&&state.nextEvents)query.set('cursor',state.nextEvents);const page=await api(`/api/cases/${state.detail.case.id}/timeline?${query}`);const events=append?[...$$('#timeline li').map(x=>x._event).filter(Boolean),...page.events]:page.events;state.nextEvents=page.next_cursor||'';renderTimeline(events,page.integrity);$$('#timeline li').forEach((li,index)=>li._event=events[index])}
function setTab(name){state.tab=name;$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$$('.tab-panel').forEach(x=>x.classList.add('hidden'));$(`#tab-${name}`).classList.remove('hidden')}
async function mutate(path,body){try{await api(path,{method:'POST',body:JSON.stringify(body)});await openCase(state.detail.case.id);await loadCases();toast('操作已保存')}catch(error){toast(error.message,true);await openCase(state.detail.case.id)}}
function escapeHTML(value){const div=document.createElement('div');div.textContent=value??'';return div.innerHTML}
async function showPreview(){const c=state.detail.case,d=await api(`/api/cases/${c.id}/declaration/preview?approver=${encodeURIComponent('质量审核员')}`);$('#preview-content').innerHTML=`<h3>${escapeHTML(d.document_title)}</h3><dl><dt>所属机构</dt><dd>${escapeHTML(d.organization)}</dd><dt>负责人</dt><dd>${escapeHTML(d.owner)}</dd><dt>规则版本</dt><dd>${escapeHTML(d.rule_version)}</dd><dt>内容修订</dt><dd>${d.content_revision}</dd><dt>审批人</dt><dd>${escapeHTML(d.approver)}</dd><dt>处置摘要</dt><dd>${d.issue_dispositions.length} 项</dd><dt>稳定摘要</dt><dd class="digest">${escapeHTML(d.digest)}</dd></dl>`;$('#preview-dialog').showModal();return d}
$('#new-case').onclick=()=>$('#case-dialog').showModal();$$('[data-close]').forEach(x=>x.onclick=()=>$('#case-dialog').close());$('#case-form').onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));values.request_id=id();try{const result=await api('/api/cases',{method:'POST',body:JSON.stringify(values)});$('#case-dialog').close();event.currentTarget.reset();await loadCases(result.case_id);toast('验收案已创建')}catch(error){toast(error.message,true)}};
$('#case-filters').onsubmit=async event=>{event.preventDefault();const next=paramsFrom(event.currentTarget);try{const data=await api(`/api/cases?${next}`);state.caseQuery=next;state.cases=data.cases;state.nextCases=data.next_cursor||'';renderCases(data.total)}catch(error){toast(error.message,true)}};$('#case-filters').onreset=()=>setTimeout(()=>{state.caseQuery=new URLSearchParams();loadCases().catch(error=>toast(error.message,true))});$('#next-cases').onclick=()=>loadCases('',true).catch(error=>toast(error.message,true));
$('#edit-case').onclick=()=>{const c=state.detail.case,form=$('#edit-form');for(const key of ['title','organization','owner','target_publish_date'])form.elements[key].value=c[key];form.elements.actor.value=c.owner;$('#edit-dialog').showModal()};$$('[data-edit-close]').forEach(x=>x.onclick=()=>$('#edit-dialog').close());$('#edit-form').onsubmit=async event=>{event.preventDefault();const c=state.detail.case,values=Object.fromEntries(new FormData(event.currentTarget));values.revision=c.revision;values.request_id=id();try{await api(`/api/cases/${c.id}`,{method:'PATCH',body:JSON.stringify(values)});$('#edit-dialog').close();await openCase(c.id);await loadCases();toast('验收案信息已更新')}catch(error){toast(error.message,true)}};
$('#add-block').onclick=()=>$('#blocks').append(blockTemplate());$('#save-content').onclick=async()=>{const c=state.detail.case;try{await api(`/api/cases/${c.id}/content`,{method:'PUT',body:JSON.stringify({revision:c.revision,actor:c.owner,request_id:id(),blocks:collectBlocks()})});await openCase(c.id);await loadCases();toast('内容修订已保存')}catch(error){toast(error.message,true)}};$('#run-audit').onclick=()=>mutate(`/api/cases/${state.detail.case.id}/audit`,{revision:state.detail.case.revision,actor:state.detail.case.owner,request_id:id()});
$('#content-history').onclick=()=>$('#history-panel').classList.toggle('hidden');$('#compare-content').onclick=async()=>{const c=state.detail.case;try{const diff=await api(`/api/cases/${c.id}/content/diff?from=${$('#diff-from').value}&to=${$('#diff-to').value}`);const node=$('#content-diff');node.textContent=JSON.stringify(diff,null,2);node.classList.remove('hidden')}catch(error){toast(error.message,true)}};
$('#batch-evidence').onclick=()=>batchEvidence();$('#batch-review').onclick=()=>batchReview();$('#preview-declaration').onclick=()=>showPreview().catch(error=>toast(error.message,true));$('#close-preview').onclick=()=>$('#preview-dialog').close();$('#approve').onclick=async()=>{try{await showPreview();if(confirm('确认按当前预览批准验收案？')){const c=state.detail.case;$('#preview-dialog').close();await mutate(`/api/cases/${c.id}/approve`,{revision:c.revision,actor:'质量审核员',request_id:id()})}}catch(error){toast(error.message,true)}};$('#publish').onclick=async()=>{const c=state.detail.case;await mutate(`/api/cases/${c.id}/publish`,{revision:c.revision,actor:'质量审核员',request_id:id()});window.open(`/cases/${c.id}/declaration`,'_blank','noopener')};
$('#timeline-filters').onsubmit=async event=>{event.preventDefault();const next=paramsFrom(event.currentTarget);try{state.timelineQuery=next;state.nextEvents='';await loadTimeline()}catch(error){toast(error.message,true)}};$('#timeline-filters').onreset=()=>setTimeout(async()=>{state.timelineQuery=new URLSearchParams();state.nextEvents='';try{await loadTimeline()}catch(error){toast(error.message,true)}});$('#next-events').onclick=()=>loadTimeline(true).catch(error=>toast(error.message,true));$$('.tab').forEach(tab=>tab.onclick=()=>setTab(tab.dataset.tab));loadCases().catch(error=>toast(error.message,true));
